name: Tests

on: [push]

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - run: pip install coverage
    - run: python -m coverage run -m unittest main_test
    - run: python -m coverage report main.py
    - run: pip install pylint
    - run: pylint $(git ls-files '*.py')
